name: Run Tests and SonarCloud Analysis backend

on:
  push:
    branches:
      - develop

jobs:
  backTest-sonarCloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "3.1.x"

      - name: Restore dependencies
        working-directory: ./backend-todo
        run: dotnet restore

      - name: Run tests and collect coverage
        working-directory: ./backend-todo
        run: |
          dotnet test ./TestGestor/TestGestor.csproj --collect:"XPlat Code Coverage" /p:CoverletOutput=./TestResults/coverage.opencover.xml /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: SonarCloud coverage for backend
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
