name: Run Tests and SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests
        working-directory: ./frontend 
        run: |
          npm install
          npm test

  sonarcloud:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 'latest'

      - name: Run tests and collect coverage
        run: |
          dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./TestResults/coverage.opencover.xml

      - name: SonarScanner for .NET
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=lenincar
            -Dsonar.projectKey=LeninCar_Gestor
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
