name: Run Tests and SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests
        working-directory: ./frontend 
        run: |
          npm install
          npm test -- --coverage
          # Move coverage report to a common location
          mkdir -p coverage/frontend
          mv coverage/lcov-report/* coverage/frontend/

  sonarcloud:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '3.1.x'

      - name: Prepare frontend coverage for SonarCloud
        run: |
          # Convert lcov to cobertura format
          npm install -g lcov-to-cobertura-xml
          lcov-to-cobertura-xml coverage/frontend/lcov.info > coverage/frontend/coverage.cobertura.xml
  

      # - name: Run tests and collect coverage
      #   working-directory: ./backend-todo/backend-todo
      #   run: |
      #     dotnet test --no-build --collect:"XPlat Code Coverage" /p:CoverletOutput=./TestResults/coverage.opencover.xml /p:CoverletOutputFormat=opencover

      - name: SonarScanner for .NET
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=lenincar
            -Dsonar.projectKey=LeninCar_Gestor
            # -Dsonar.coverageReportPaths=./backend-todo/backend-todo/TestResults/coverage.opencover.xml
            -Dsonar.javascript.lcov.reportPaths=./frontend/coverage/frontend/lcov.info
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
