name: Run Tests and SonarCloud Analysis

on:
  push:
    branches:
      - master
      - feature/lenin

jobs:
  frontTest-sonarCloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and run tests
        working-directory: ./frontend 
        run: |
          npm install
          npm test -- --coverage --watchAll=false

  backTest-sonarCloud:
    runs-on: ubuntu-latest
    needs: frontTest-sonarCloud

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run tests and collect coverage
        working-directory: ./backend-todo
        run: |
          dotnet test ./TestGestor/TestGestor.csproj --collect:"XPlat Code Coverage" /p:CoverletOutput=./TestResults/coverage.opencover.xml /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          

  sonarCloud:
    runs-on: ubuntu-latest
    needs: [frontTest-sonarCloud, backTest-sonarCloud]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud coverage
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
