name: Run Tests and SonarCloud Analysis

on:
  push:
    branches:
      - develop

jobs:
  frontTest-sonarCloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and run tests
        working-directory: ./frontend
        run: |
          npm install
          npm test -- --coverage --watchAll=false

  backendTest-sonarCloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "3.1.x"

      - name: Restore dependencies
        working-directory: ./backend-todo
        run: dotnet restore

      - name: Run tests and collect coverage
        working-directory: ./backend-todo
        run: |
          dotnet test ./TestGestor/TestGestor.csproj --collect:"XPlat Code Coverage" /p:CoverletOutput=./TestResults/ /p:CoverletOutputFormat=opencover

      - name: SonarCloud coverage for backend
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=my_project_key_backend
            -Dsonar.organization=my_organization
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.cs.opencover.reportsPaths=./backend-todo/TestResults/coverage.opencover.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
